In [2]:
pip install -r requirements.txt

Requirement already satisfied: numpy in /opt/anaconda3/lib/python3.8/site-packages (from -r requirements.txt (line 1)) (1.18.5)
Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.8/site-packages (from -r requirements.txt (line 2)) (1.0.5)
Requirement already satisfied: seaborn in /opt/anaconda3/lib/python3.8/site-packages (from -r requirements.txt (line 3)) (0.10.1)
Requirement already satisfied: matplotlib in /opt/anaconda3/lib/python3.8/site-packages (from -r requirements.txt (line 4)) (3.2.2)
Requirement already satisfied: siuba in /opt/anaconda3/lib/python3.8/site-packages (from -r requirements.txt (line 5)) (0.0.24)
Requirement already satisfied: CensusData in /opt/anaconda3/lib/python3.8/site-packages (from -r requirements.txt (line 6)) (1.13)
Requirement already satisfied: python-dateutil>=2.6.1 in /opt/anaconda3/lib/python3.8/site-packages (from pandas->-r requirements.txt (line 2)) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in /opt/anaconda3/lib/python3.8/site-packages (from pandas->-r requirements.txt (line 2)) (2020.1)
Requirement already satisfied: scipy>=1.0.1 in /opt/anaconda3/lib/python3.8/site-packages (from seaborn->-r requirements.txt (line 3)) (1.5.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /opt/anaconda3/lib/python3.8/site-packages (from matplotlib->-r requirements.txt (line 4)) (1.2.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /opt/anaconda3/lib/python3.8/site-packages (from matplotlib->-r requirements.txt (line 4)) (2.4.7)
Requirement already satisfied: cycler>=0.10 in /opt/anaconda3/lib/python3.8/site-packages (from matplotlib->-r requirements.txt (line 4)) (0.10.0)
Requirement already satisfied: SQLAlchemy>=1.1.18 in /opt/anaconda3/lib/python3.8/site-packages (from siuba->-r requirements.txt (line 5)) (1.3.18)
Requirement already satisfied: PyYAML>=3.0.0 in /opt/anaconda3/lib/python3.8/site-packages (from siuba->-r requirements.txt (line 5)) (5.3.1)
Requirement already satisfied: requests in /opt/anaconda3/lib/python3.8/site-packages (from CensusData->-r requirements.txt (line 6)) (2.20.0)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.8/site-packages (from python-dateutil>=2.6.1->pandas->-r requirements.txt (line 2)) (1.15.0)
Requirement already satisfied: idna<2.8,>=2.5 in /opt/anaconda3/lib/python3.8/site-packages (from requests->CensusData->-r requirements.txt (line 6)) (2.7)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /opt/anaconda3/lib/python3.8/site-packages (from requests->CensusData->-r requirements.txt (line 6)) (1.24.3)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.8/site-packages (from requests->CensusData->-r requirements.txt (line 6)) (2020.6.20)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /opt/anaconda3/lib/python3.8/site-packages (from requests->CensusData->-r requirements.txt (line 6)) (3.0.4)
Note: you may need to restart the kernel to use updated packages.

In [10]:
import censusdata as cd
import numpy as np

In [4]:
# B01001_001E (total population)
# B01001H_001E (total white only, not hispanic or latino)
# B01001B_001E (total black only)
# B01001D_001E (total asian only)
# B01001I_001E (total hispanic or latino)

# B06011_001E (median income)
# B06011_005E (median income - foreign born)
# B06012_002E (total below 100% of poverty level)
# B06012_018E (total below 100% of poverty level - foreign born)

# B15003_017E (HS diploma)
# B15003_022E (college degree)

# B23025_001E (population 16+)
# B23025_002E (population 16+ in labor force)
# B23025_007E (population 16+ not in labor force)

# B27001_001E (surveyed pop for health insurance)
# B27011_004E (employed with public/private health insurance)
# B27011_005E (employed with private insurance)
# B27011_006E (employed with public insurance)
# B27011_007E (emplyoed no insurance)
# B27011_012E (unemployed no insurance)
# B27011_017E (not in labor force no insurance)

demographics = cd.download('acs5', 2019,
                             cd.censusgeo([('state', '06'), ('county', '*')]),
                             ['B01001_001E','B01001H_001E','B01001B_001E','B01001D_001E','B01001I_001E',
                              'B06011_001E','B06011_005E','B06012_002E','B06012_018E',
                              'B15003_017E','B15003_022E',
                              'B23025_001E','B23025_002E','B23025_007E',
                              'B27001_001E','B27011_004E','B27011_005E','B27011_006E','B27011_007E','B27011_012E','B27011_017E'])

In [5]:
demographics.columns = ['TotalPopulation', 'TotalWhiteNotHispanic', 'TotalBlack', 'TotalAsian', 'TotalHispanicLatino',
                        'MedianIncome', 'MedianIncomeForeignBorn', 'TotalBelowPovertyLine', 'TotalForeignBornBelowPoveryLine',
                        'TotalHSDiploma', 'TotalBachelorsDegree',
                        'TotalPop16Above', 'TotalPop16AboveInLaborForce', 'TotalPop16AboveNotInLaborForce',
                        'TotalPopSurveyInsurance', 'TotalEmployedWithInsurance', 
                        'TotalEmployedWithInsurancePrivate', 'TotalEmployedWithInsurancePublic', 
                        'TotalEmployedNoInsurance', 'TotalUnemployedNoInsurance', 'TotalNotInLaborForceNoInsurance']

demographics = demographics.reset_index()

demographics['FullCounty'] = demographics['index'].astype(str).str.split(',').str[0]

demographics['index'] = demographics['index'].astype(str).str.split(' ').str[0]

demographics.rename(columns = {'index':'County'}, inplace = True)

In [6]:
demographics.head()

,County,TotalPopulation,TotalWhiteNotHispanic,TotalBlack,TotalAsian,TotalHispanicLatino,MedianIncome,MedianIncomeForeignBorn,TotalBelowPovertyLine,TotalForeignBornBelowPoveryLine,...,TotalPop16AboveInLaborForce,TotalPop16AboveNotInLaborForce,TotalPopSurveyInsurance,TotalEmployedWithInsurance,TotalEmployedWithInsurancePrivate,TotalEmployedWithInsurancePublic,TotalEmployedNoInsurance,TotalUnemployedNoInsurance,TotalNotInLaborForceNoInsurance,FullCounty
0,Merced,271382,75037,8645,20349,161814,24873,23473,56217,13949,...,119232,80520,268611,86714,64991,24869,12354,1911,4818,Merced County
1,Mariposa,17420,13935,253,210,1963,27678,26197,2616,116,...,7672,7138,17256,5627,4622,1160,527,69,320,Mariposa County
2,Modoc,8907,6920,136,99,1291,25106,17611,1618,165,...,3235,4130,8698,2272,1725,617,329,13,304,Modoc County
3,Contra,1142251,500592,99642,190983,292298,42181,37810,98595,29750,...,591383,320638,1137149,483189,436767,57661,32955,3936,12467,Contra Costa County
4,Inyo,17977,11173,153,350,4020,31566,31792,1635,163,...,8593,6157,17607,6924,6110,996,712,37,155,Inyo County

In [14]:
demographics.describe()

,TotalPopulation,TotalWhiteNotHispanic,TotalBlack,TotalAsian,TotalHispanicLatino,MedianIncome,MedianIncomeForeignBorn,TotalBelowPovertyLine,TotalForeignBornBelowPoveryLine,TotalHSDiploma,...,TotalPop16Above,TotalPop16AboveInLaborForce,TotalPop16AboveNotInLaborForce,TotalPopSurveyInsurance,TotalEmployedWithInsurance,TotalEmployedWithInsurancePrivate,TotalEmployedWithInsurancePublic,TotalEmployedNoInsurance,TotalUnemployedNoInsurance,TotalNotInLaborForceNoInsurance
count,5.800000e+01,5.800000e+01,58.000000,5.800000e+01,5.800000e+01,58.000000,5.800000e+01,5.800000e+01,58.000000,5.800000e+01,...,5.800000e+01,5.800000e+01,5.800000e+01,5.800000e+01,5.800000e+01,5.800000e+01,58.000000,58.000000,58.000000,58.000000
mean,6.773017e+05,2.518157e+05,39208.758621,9.814522e+04,2.642705e+05,30963.620690,-1.146759e+07,8.878866e+04,26633.396552,8.298707e+04,...,5.393908e+05,3.434749e+05,1.959159e+05,6.687472e+05,2.700205e+05,2.310899e+05,45866.758621,29411.465517,3453.982759,10981.706897
std,1.469524e+06,4.362806e+05,114855.088637,2.389240e+05,6.845517e+05,7354.083205,8.754118e+07,2.079402e+05,75887.363799,1.862458e+05,...,1.180864e+06,7.653985e+05,4.162612e+05,1.457003e+06,5.940364e+05,5.013539e+05,108132.041837,81429.673384,8575.534364,28847.141339
min,1.039000e+03,5.510000e+02,2.000000,0.000000e+00,1.300000e+02,18245.000000,-6.666667e+08,2.050000e+02,0.000000,1.730000e+02,...,8.530000e+02,3.920000e+02,4.610000e+02,1.039000e+03,2.330000e+02,1.900000e+02,68.000000,38.000000,8.000000,38.000000
25%,4.764675e+04,3.079650e+04,644.750000,7.717500e+02,9.949750e+03,25765.500000,2.308900e+04,5.471000e+03,548.750000,8.501250e+03,...,4.058400e+04,1.936000e+04,1.901325e+04,4.657675e+04,1.507150e+04,1.280825e+04,3084.250000,1487.000000,247.000000,691.750000
50%,1.846320e+05,1.012650e+05,3975.000000,1.036400e+04,5.075650e+04,29496.500000,2.599600e+04,2.934800e+04,4254.000000,2.147500e+04,...,1.501525e+05,8.436300e+04,6.578950e+04,1.825205e+05,6.652900e+04,5.971300e+04,13602.500000,6234.000000,778.000000,2623.500000
75%,6.927508e+05,2.872638e+05,17474.750000,5.716750e+04,2.535352e+05,33250.000000,3.049875e+04,7.972250e+04,20836.500000,7.332025e+04,...,5.250925e+05,3.220018e+05,1.862992e+05,6.844030e+05,2.540648e+05,2.105365e+05,44803.750000,22948.000000,3036.000000,8466.750000
max,1.008157e+07,2.641770e+06,820478.000000,1.473221e+06,4.888434e+06,52866.000000,4.885200e+04,1.480446e+06,553580.000000,1.296682e+06,...,8.123894e+06,5.253694e+06,2.870200e+06,1.001290e+07,4.049389e+06,3.366147e+06,769892.000000,588450.000000,60308.000000,205209.000000

In [23]:
demographics.loc[(demographics.MedianIncomeForeignBorn == -666666666),'MedianIncomeForeignBorn'] = np.NaN

In [24]:
demographics.to_csv('cleaned_data/census_demographics.csv', encoding = 'utf-8', index = False)